/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/diagnostic_msgs/cmake/../msg/DiagnosticArray.msg */
#ifndef DIAGNOSTIC_MSGS_BOOST_SERIALIZATION_DIAGNOSTICARRAY_H
#define DIAGNOSTIC_MSGS_BOOST_SERIALIZATION_DIAGNOSTICARRAY_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <diagnostic_msgs/DiagnosticArray.h>
#include <std_msgs/boost/Header.h>
#include <diagnostic_msgs/boost/DiagnosticStatus.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::diagnostic_msgs::DiagnosticArray_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("status",m.status);
}

} // namespace serialization
} // namespace boost

#endif // DIAGNOSTIC_MSGS_BOOST_SERIALIZATION_DIAGNOSTICARRAY_H

