/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/diagnostic_msgs/cmake/../msg/KeyValue.msg */
#ifndef DIAGNOSTIC_MSGS_BOOST_SERIALIZATION_KEYVALUE_H
#define DIAGNOSTIC_MSGS_BOOST_SERIALIZATION_KEYVALUE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <diagnostic_msgs/KeyValue.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::diagnostic_msgs::KeyValue_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("key",m.key);
    a & make_nvp("value",m.value);
}

} // namespace serialization
} // namespace boost

#endif // DIAGNOSTIC_MSGS_BOOST_SERIALIZATION_KEYVALUE_H

