(cl:defpackage rtt_actionlib_examples-msg
  (:use )
  (:export
   "<SOMEACTIONACTION>"
   "SOMEACTIONACTION"
   "<SOMEACTIONGOAL>"
   "SOMEACTIONGOAL"
   "<SOMEACTIONACTIONGOAL>"
   "SOMEACTIONACTIONGOAL"
   "<SOMEACTIONRESULT>"
   "SOMEACTIONRESULT"
   "<SOMEACTIONACTIONRESULT>"
   "SOMEACTIONACTIONRESULT"
   "<SOMEACTIONFEEDBACK>"
   "SOMEACTIONFEEDBACK"
   "<SOMEACTIONACTIONFEEDBACK>"
   "SOMEACTIONACTIONFEEDBACK"
  ))

