; Auto-generated. Do not edit!


(cl:in-package rtt_actionlib_examples-msg)


;//! \htmlinclude SomeActionGoal.msg.html

(cl:defclass <SomeActionGoal> (roslisp-msg-protocol:ros-message)
  ((delay_time
    :reader delay_time
    :initarg :delay_time
    :type cl:real
    :initform 0))
)

(cl:defclass SomeActionGoal (<SomeActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SomeActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SomeActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rtt_actionlib_examples-msg:<SomeActionGoal> is deprecated: use rtt_actionlib_examples-msg:SomeActionGoal instead.")))

(cl:ensure-generic-function 'delay_time-val :lambda-list '(m))
(cl:defmethod delay_time-val ((m <SomeActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rtt_actionlib_examples-msg:delay_time-val is deprecated.  Use rtt_actionlib_examples-msg:delay_time instead.")
  (delay_time m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SomeActionGoal>) ostream)
  "Serializes a message object of type '<SomeActionGoal>"
  (cl:let ((__sec (cl:floor (cl:slot-value msg 'delay_time)))
        (__nsec (cl:round (cl:* 1e9 (cl:- (cl:slot-value msg 'delay_time) (cl:floor (cl:slot-value msg 'delay_time)))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SomeActionGoal>) istream)
  "Deserializes a message object of type '<SomeActionGoal>"
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'delay_time) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SomeActionGoal>)))
  "Returns string type for a message object of type '<SomeActionGoal>"
  "rtt_actionlib_examples/SomeActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SomeActionGoal)))
  "Returns string type for a message object of type 'SomeActionGoal"
  "rtt_actionlib_examples/SomeActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SomeActionGoal>)))
  "Returns md5sum for a message object of type '<SomeActionGoal>"
  "b58939b0c4ec968ed323f9719f7bfcfc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SomeActionGoal)))
  "Returns md5sum for a message object of type 'SomeActionGoal"
  "b58939b0c4ec968ed323f9719f7bfcfc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SomeActionGoal>)))
  "Returns full string definition for message of type '<SomeActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%duration delay_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SomeActionGoal)))
  "Returns full string definition for message of type 'SomeActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%duration delay_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SomeActionGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SomeActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SomeActionGoal
    (cl:cons ':delay_time (delay_time msg))
))
