/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/nav_msgs/cmake/../msg/GetMapResult.msg */
#ifndef NAV_MSGS_BOOST_SERIALIZATION_GETMAPRESULT_H
#define NAV_MSGS_BOOST_SERIALIZATION_GETMAPRESULT_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <nav_msgs/GetMapResult.h>
#include <nav_msgs/boost/OccupancyGrid.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::nav_msgs::GetMapResult_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("map",m.map);
}

} // namespace serialization
} // namespace boost

#endif // NAV_MSGS_BOOST_SERIALIZATION_GETMAPRESULT_H

