/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/nav_msgs/cmake/../msg/GetMapAction.msg */
#ifndef NAV_MSGS_BOOST_SERIALIZATION_GETMAPACTION_H
#define NAV_MSGS_BOOST_SERIALIZATION_GETMAPACTION_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <nav_msgs/GetMapAction.h>
#include <nav_msgs/boost/GetMapActionGoal.h>
#include <nav_msgs/boost/GetMapActionResult.h>
#include <nav_msgs/boost/GetMapActionFeedback.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::nav_msgs::GetMapAction_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("action_goal",m.action_goal);
    a & make_nvp("action_result",m.action_result);
    a & make_nvp("action_feedback",m.action_feedback);
}

} // namespace serialization
} // namespace boost

#endif // NAV_MSGS_BOOST_SERIALIZATION_GETMAPACTION_H

