/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/nav_msgs/cmake/../msg/GetMapActionResult.msg */
#ifndef NAV_MSGS_BOOST_SERIALIZATION_GETMAPACTIONRESULT_H
#define NAV_MSGS_BOOST_SERIALIZATION_GETMAPACTIONRESULT_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <nav_msgs/GetMapActionResult.h>
#include <std_msgs/boost/Header.h>
#include <actionlib_msgs/boost/GoalStatus.h>
#include <nav_msgs/boost/GetMapResult.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::nav_msgs::GetMapActionResult_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("status",m.status);
    a & make_nvp("result",m.result);
}

} // namespace serialization
} // namespace boost

#endif // NAV_MSGS_BOOST_SERIALIZATION_GETMAPACTIONRESULT_H

