/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/nav_msgs/cmake/../msg/GetMapGoal.msg */
#ifndef NAV_MSGS_BOOST_SERIALIZATION_GETMAPGOAL_H
#define NAV_MSGS_BOOST_SERIALIZATION_GETMAPGOAL_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <nav_msgs/GetMapGoal.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::nav_msgs::GetMapGoal_<ContainerAllocator>  & m, unsigned int)
{
}

} // namespace serialization
} // namespace boost

#endif // NAV_MSGS_BOOST_SERIALIZATION_GETMAPGOAL_H

