/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/nav_msgs/cmake/../msg/GetMapActionGoal.msg */
#ifndef NAV_MSGS_BOOST_SERIALIZATION_GETMAPACTIONGOAL_H
#define NAV_MSGS_BOOST_SERIALIZATION_GETMAPACTIONGOAL_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <nav_msgs/GetMapActionGoal.h>
#include <std_msgs/boost/Header.h>
#include <actionlib_msgs/boost/GoalID.h>
#include <nav_msgs/boost/GetMapGoal.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::nav_msgs::GetMapActionGoal_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("goal_id",m.goal_id);
    a & make_nvp("goal",m.goal);
}

} // namespace serialization
} // namespace boost

#endif // NAV_MSGS_BOOST_SERIALIZATION_GETMAPACTIONGOAL_H

