/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/nav_msgs/cmake/../msg/GridCells.msg */
#ifndef NAV_MSGS_BOOST_SERIALIZATION_GRIDCELLS_H
#define NAV_MSGS_BOOST_SERIALIZATION_GRIDCELLS_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <nav_msgs/GridCells.h>
#include <std_msgs/boost/Header.h>
#include <geometry_msgs/boost/Point.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::nav_msgs::GridCells_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("cell_width",m.cell_width);
    a & make_nvp("cell_height",m.cell_height);
    a & make_nvp("cells",m.cells);
}

} // namespace serialization
} // namespace boost

#endif // NAV_MSGS_BOOST_SERIALIZATION_GRIDCELLS_H

