/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/nav_msgs/cmake/../msg/OccupancyGrid.msg */
#ifndef NAV_MSGS_BOOST_SERIALIZATION_OCCUPANCYGRID_H
#define NAV_MSGS_BOOST_SERIALIZATION_OCCUPANCYGRID_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <nav_msgs/OccupancyGrid.h>
#include <std_msgs/boost/Header.h>
#include <nav_msgs/boost/MapMetaData.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("info",m.info);
    a & make_nvp("data",m.data);
}

} // namespace serialization
} // namespace boost

#endif // NAV_MSGS_BOOST_SERIALIZATION_OCCUPANCYGRID_H

