/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/nav_msgs/cmake/../msg/Odometry.msg */
#ifndef NAV_MSGS_BOOST_SERIALIZATION_ODOMETRY_H
#define NAV_MSGS_BOOST_SERIALIZATION_ODOMETRY_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <nav_msgs/Odometry.h>
#include <std_msgs/boost/Header.h>
#include <geometry_msgs/boost/PoseWithCovariance.h>
#include <geometry_msgs/boost/TwistWithCovariance.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::nav_msgs::Odometry_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("child_frame_id",m.child_frame_id);
    a & make_nvp("pose",m.pose);
    a & make_nvp("twist",m.twist);
}

} // namespace serialization
} // namespace boost

#endif // NAV_MSGS_BOOST_SERIALIZATION_ODOMETRY_H

