/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/actionlib_msgs/cmake/../msg/GoalID.msg */
#ifndef ACTIONLIB_MSGS_BOOST_SERIALIZATION_GOALID_H
#define ACTIONLIB_MSGS_BOOST_SERIALIZATION_GOALID_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <actionlib_msgs/GoalID.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::actionlib_msgs::GoalID_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("stamp",m.stamp);
    a & make_nvp("id",m.id);
}

} // namespace serialization
} // namespace boost

#endif // ACTIONLIB_MSGS_BOOST_SERIALIZATION_GOALID_H

