/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/actionlib_msgs/cmake/../msg/GoalStatusArray.msg */
#ifndef ACTIONLIB_MSGS_BOOST_SERIALIZATION_GOALSTATUSARRAY_H
#define ACTIONLIB_MSGS_BOOST_SERIALIZATION_GOALSTATUSARRAY_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <actionlib_msgs/GoalStatusArray.h>
#include <std_msgs/boost/Header.h>
#include <actionlib_msgs/boost/GoalStatus.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::actionlib_msgs::GoalStatusArray_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("status_list",m.status_list);
}

} // namespace serialization
} // namespace boost

#endif // ACTIONLIB_MSGS_BOOST_SERIALIZATION_GOALSTATUSARRAY_H

