/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/actionlib_msgs/cmake/../msg/GoalStatus.msg */
#ifndef ACTIONLIB_MSGS_BOOST_SERIALIZATION_GOALSTATUS_H
#define ACTIONLIB_MSGS_BOOST_SERIALIZATION_GOALSTATUS_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <actionlib_msgs/GoalStatus.h>
#include <actionlib_msgs/boost/GoalID.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::actionlib_msgs::GoalStatus_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("goal_id",m.goal_id);
    a & make_nvp("status",m.status);
    a & make_nvp("text",m.text);
}

} // namespace serialization
} // namespace boost

#endif // ACTIONLIB_MSGS_BOOST_SERIALIZATION_GOALSTATUS_H

