/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/stereo_msgs/cmake/../msg/DisparityImage.msg */
#ifndef STEREO_MSGS_BOOST_SERIALIZATION_DISPARITYIMAGE_H
#define STEREO_MSGS_BOOST_SERIALIZATION_DISPARITYIMAGE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <stereo_msgs/DisparityImage.h>
#include <std_msgs/boost/Header.h>
#include <sensor_msgs/boost/Image.h>
#include <sensor_msgs/boost/RegionOfInterest.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::stereo_msgs::DisparityImage_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("image",m.image);
    a & make_nvp("f",m.f);
    a & make_nvp("T",m.T);
    a & make_nvp("valid_window",m.valid_window);
    a & make_nvp("min_disparity",m.min_disparity);
    a & make_nvp("max_disparity",m.max_disparity);
    a & make_nvp("delta_d",m.delta_d);
}

} // namespace serialization
} // namespace boost

#endif // STEREO_MSGS_BOOST_SERIALIZATION_DISPARITYIMAGE_H

