/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/visualization_msgs/cmake/../msg/InteractiveMarkerFeedback.msg */
#ifndef VISUALIZATION_MSGS_BOOST_SERIALIZATION_INTERACTIVEMARKERFEEDBACK_H
#define VISUALIZATION_MSGS_BOOST_SERIALIZATION_INTERACTIVEMARKERFEEDBACK_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <visualization_msgs/InteractiveMarkerFeedback.h>
#include <std_msgs/boost/Header.h>
#include <geometry_msgs/boost/Pose.h>
#include <geometry_msgs/boost/Point.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::visualization_msgs::InteractiveMarkerFeedback_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("client_id",m.client_id);
    a & make_nvp("marker_name",m.marker_name);
    a & make_nvp("control_name",m.control_name);
    a & make_nvp("event_type",m.event_type);
    a & make_nvp("pose",m.pose);
    a & make_nvp("menu_entry_id",m.menu_entry_id);
    a & make_nvp("mouse_point",m.mouse_point);
    a & make_nvp("mouse_point_valid",m.mouse_point_valid);
}

} // namespace serialization
} // namespace boost

#endif // VISUALIZATION_MSGS_BOOST_SERIALIZATION_INTERACTIVEMARKERFEEDBACK_H

