/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/visualization_msgs/cmake/../msg/InteractiveMarkerControl.msg */
#ifndef VISUALIZATION_MSGS_BOOST_SERIALIZATION_INTERACTIVEMARKERCONTROL_H
#define VISUALIZATION_MSGS_BOOST_SERIALIZATION_INTERACTIVEMARKERCONTROL_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <visualization_msgs/InteractiveMarkerControl.h>
#include <geometry_msgs/boost/Quaternion.h>
#include <visualization_msgs/boost/Marker.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::visualization_msgs::InteractiveMarkerControl_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("name",m.name);
    a & make_nvp("orientation",m.orientation);
    a & make_nvp("orientation_mode",m.orientation_mode);
    a & make_nvp("interaction_mode",m.interaction_mode);
    a & make_nvp("always_visible",m.always_visible);
    a & make_nvp("markers",m.markers);
    a & make_nvp("independent_marker_orientation",m.independent_marker_orientation);
    a & make_nvp("description",m.description);
}

} // namespace serialization
} // namespace boost

#endif // VISUALIZATION_MSGS_BOOST_SERIALIZATION_INTERACTIVEMARKERCONTROL_H

