/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/visualization_msgs/cmake/../msg/InteractiveMarkerPose.msg */
#ifndef VISUALIZATION_MSGS_BOOST_SERIALIZATION_INTERACTIVEMARKERPOSE_H
#define VISUALIZATION_MSGS_BOOST_SERIALIZATION_INTERACTIVEMARKERPOSE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <visualization_msgs/InteractiveMarkerPose.h>
#include <std_msgs/boost/Header.h>
#include <geometry_msgs/boost/Pose.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::visualization_msgs::InteractiveMarkerPose_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("pose",m.pose);
    a & make_nvp("name",m.name);
}

} // namespace serialization
} // namespace boost

#endif // VISUALIZATION_MSGS_BOOST_SERIALIZATION_INTERACTIVEMARKERPOSE_H

