/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/visualization_msgs/cmake/../msg/InteractiveMarkerInit.msg */
#ifndef VISUALIZATION_MSGS_BOOST_SERIALIZATION_INTERACTIVEMARKERINIT_H
#define VISUALIZATION_MSGS_BOOST_SERIALIZATION_INTERACTIVEMARKERINIT_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <visualization_msgs/InteractiveMarkerInit.h>
#include <visualization_msgs/boost/InteractiveMarker.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::visualization_msgs::InteractiveMarkerInit_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("server_id",m.server_id);
    a & make_nvp("seq_num",m.seq_num);
    a & make_nvp("markers",m.markers);
}

} // namespace serialization
} // namespace boost

#endif // VISUALIZATION_MSGS_BOOST_SERIALIZATION_INTERACTIVEMARKERINIT_H

