/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/visualization_msgs/cmake/../msg/MarkerArray.msg */
#ifndef VISUALIZATION_MSGS_BOOST_SERIALIZATION_MARKERARRAY_H
#define VISUALIZATION_MSGS_BOOST_SERIALIZATION_MARKERARRAY_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <visualization_msgs/MarkerArray.h>
#include <visualization_msgs/boost/Marker.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::visualization_msgs::MarkerArray_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("markers",m.markers);
}

} // namespace serialization
} // namespace boost

#endif // VISUALIZATION_MSGS_BOOST_SERIALIZATION_MARKERARRAY_H

