/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/shape_msgs/cmake/../msg/MeshTriangle.msg */
#ifndef SHAPE_MSGS_BOOST_SERIALIZATION_MESHTRIANGLE_H
#define SHAPE_MSGS_BOOST_SERIALIZATION_MESHTRIANGLE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <shape_msgs/MeshTriangle.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::shape_msgs::MeshTriangle_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("vertex_indices",m.vertex_indices);
}

} // namespace serialization
} // namespace boost

#endif // SHAPE_MSGS_BOOST_SERIALIZATION_MESHTRIANGLE_H

