/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/shape_msgs/cmake/../msg/Mesh.msg */
#ifndef SHAPE_MSGS_BOOST_SERIALIZATION_MESH_H
#define SHAPE_MSGS_BOOST_SERIALIZATION_MESH_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <shape_msgs/Mesh.h>
#include <shape_msgs/boost/MeshTriangle.h>
#include <geometry_msgs/boost/Point.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::shape_msgs::Mesh_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("triangles",m.triangles);
    a & make_nvp("vertices",m.vertices);
}

} // namespace serialization
} // namespace boost

#endif // SHAPE_MSGS_BOOST_SERIALIZATION_MESH_H

