/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/shape_msgs/cmake/../msg/Plane.msg */
#ifndef SHAPE_MSGS_BOOST_SERIALIZATION_PLANE_H
#define SHAPE_MSGS_BOOST_SERIALIZATION_PLANE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <shape_msgs/Plane.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::shape_msgs::Plane_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("coef",m.coef);
}

} // namespace serialization
} // namespace boost

#endif // SHAPE_MSGS_BOOST_SERIALIZATION_PLANE_H

