/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/shape_msgs/cmake/../msg/SolidPrimitive.msg */
#ifndef SHAPE_MSGS_BOOST_SERIALIZATION_SOLIDPRIMITIVE_H
#define SHAPE_MSGS_BOOST_SERIALIZATION_SOLIDPRIMITIVE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <shape_msgs/SolidPrimitive.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::shape_msgs::SolidPrimitive_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("type",m.type);
    a & make_nvp("dimensions",m.dimensions);
}

} // namespace serialization
} // namespace boost

#endif // SHAPE_MSGS_BOOST_SERIALIZATION_SOLIDPRIMITIVE_H

