/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/std_msgs/cmake/../msg/ColorRGBA.msg */
#ifndef STD_MSGS_BOOST_SERIALIZATION_COLORRGBA_H
#define STD_MSGS_BOOST_SERIALIZATION_COLORRGBA_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <std_msgs/ColorRGBA.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::std_msgs::ColorRGBA_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("r",m.r);
    a & make_nvp("g",m.g);
    a & make_nvp("b",m.b);
    a & make_nvp("a",m.a);
}

} // namespace serialization
} // namespace boost

#endif // STD_MSGS_BOOST_SERIALIZATION_COLORRGBA_H

