/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/std_msgs/cmake/../msg/Header.msg */
#ifndef STD_MSGS_BOOST_SERIALIZATION_HEADER_H
#define STD_MSGS_BOOST_SERIALIZATION_HEADER_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <std_msgs/Header.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::std_msgs::Header_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("seq",m.seq);
    a & make_nvp("stamp",m.stamp);
    a & make_nvp("frame_id",m.frame_id);
}

} // namespace serialization
} // namespace boost

#endif // STD_MSGS_BOOST_SERIALIZATION_HEADER_H

