/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/std_msgs/cmake/../msg/Int32.msg */
#ifndef STD_MSGS_BOOST_SERIALIZATION_INT32_H
#define STD_MSGS_BOOST_SERIALIZATION_INT32_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <std_msgs/Int32.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::std_msgs::Int32_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("data",m.data);
}

} // namespace serialization
} // namespace boost

#endif // STD_MSGS_BOOST_SERIALIZATION_INT32_H

