/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/std_msgs/cmake/../msg/MultiArrayLayout.msg */
#ifndef STD_MSGS_BOOST_SERIALIZATION_MULTIARRAYLAYOUT_H
#define STD_MSGS_BOOST_SERIALIZATION_MULTIARRAYLAYOUT_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <std_msgs/MultiArrayLayout.h>
#include <std_msgs/boost/MultiArrayDimension.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::std_msgs::MultiArrayLayout_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("dim",m.dim);
    a & make_nvp("data_offset",m.data_offset);
}

} // namespace serialization
} // namespace boost

#endif // STD_MSGS_BOOST_SERIALIZATION_MULTIARRAYLAYOUT_H

