/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/std_msgs/cmake/../msg/MultiArrayDimension.msg */
#ifndef STD_MSGS_BOOST_SERIALIZATION_MULTIARRAYDIMENSION_H
#define STD_MSGS_BOOST_SERIALIZATION_MULTIARRAYDIMENSION_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <std_msgs/MultiArrayDimension.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::std_msgs::MultiArrayDimension_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("label",m.label);
    a & make_nvp("size",m.size);
    a & make_nvp("stride",m.stride);
}

} // namespace serialization
} // namespace boost

#endif // STD_MSGS_BOOST_SERIALIZATION_MULTIARRAYDIMENSION_H

