/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/std_msgs/cmake/../msg/UInt32.msg */
#ifndef STD_MSGS_BOOST_SERIALIZATION_UINT32_H
#define STD_MSGS_BOOST_SERIALIZATION_UINT32_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <std_msgs/UInt32.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::std_msgs::UInt32_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("data",m.data);
}

} // namespace serialization
} // namespace boost

#endif // STD_MSGS_BOOST_SERIALIZATION_UINT32_H

