/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/tpokorsk/ros-orocos-workspace/example/devel/share/rtt_actionlib_examples/msg/SomeActionFeedback.msg
 *
 */


#ifndef RTT_ACTIONLIB_EXAMPLES_MESSAGE_SOMEACTIONFEEDBACK_H
#define RTT_ACTIONLIB_EXAMPLES_MESSAGE_SOMEACTIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rtt_actionlib_examples
{
template <class ContainerAllocator>
struct SomeActionFeedback_
{
  typedef SomeActionFeedback_<ContainerAllocator> Type;

  SomeActionFeedback_()
    : percent_complete(0.0)  {
    }
  SomeActionFeedback_(const ContainerAllocator& _alloc)
    : percent_complete(0.0)  {
    }



   typedef double _percent_complete_type;
  _percent_complete_type percent_complete;




  typedef boost::shared_ptr< ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct SomeActionFeedback_

typedef ::rtt_actionlib_examples::SomeActionFeedback_<std::allocator<void> > SomeActionFeedback;

typedef boost::shared_ptr< ::rtt_actionlib_examples::SomeActionFeedback > SomeActionFeedbackPtr;
typedef boost::shared_ptr< ::rtt_actionlib_examples::SomeActionFeedback const> SomeActionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rtt_actionlib_examples

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'rtt_actionlib_examples': ['/home/tpokorsk/ros-orocos-workspace/example/devel/share/rtt_actionlib_examples/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc6abe8bc172f00995b2c3f53015f718";
  }

  static const char* value(const ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc6abe8bc172f009ULL;
  static const uint64_t static_value2 = 0x95b2c3f53015f718ULL;
};

template<class ContainerAllocator>
struct DataType< ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rtt_actionlib_examples/SomeActionFeedback";
  }

  static const char* value(const ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
float64 percent_complete\n\
\n\
\n\
";
  }

  static const char* value(const ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SomeActionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent_complete: ";
    Printer<double>::stream(s, indent + "  ", v.percent_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RTT_ACTIONLIB_EXAMPLES_MESSAGE_SOMEACTIONFEEDBACK_H
