/* Auto-generated by create_boost_header.py for file /home/tpokorsk/ros-orocos-workspace/example/devel/share/rtt_actionlib_examples/msg/SomeActionFeedback.msg */
#ifndef RTT_ACTIONLIB_EXAMPLES_BOOST_SERIALIZATION_SOMEACTIONFEEDBACK_H
#define RTT_ACTIONLIB_EXAMPLES_BOOST_SERIALIZATION_SOMEACTIONFEEDBACK_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <rtt_actionlib_examples/SomeActionFeedback.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::rtt_actionlib_examples::SomeActionFeedback_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("percent_complete",m.percent_complete);
}

} // namespace serialization
} // namespace boost

#endif // RTT_ACTIONLIB_EXAMPLES_BOOST_SERIALIZATION_SOMEACTIONFEEDBACK_H

