; Auto-generated. Do not edit!


(cl:in-package rtt_actionlib_examples-msg)


;//! \htmlinclude SomeActionResult.msg.html

(cl:defclass <SomeActionResult> (roslisp-msg-protocol:ros-message)
  ((actual_delay_time
    :reader actual_delay_time
    :initarg :actual_delay_time
    :type cl:real
    :initform 0))
)

(cl:defclass SomeActionResult (<SomeActionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SomeActionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SomeActionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rtt_actionlib_examples-msg:<SomeActionResult> is deprecated: use rtt_actionlib_examples-msg:SomeActionResult instead.")))

(cl:ensure-generic-function 'actual_delay_time-val :lambda-list '(m))
(cl:defmethod actual_delay_time-val ((m <SomeActionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rtt_actionlib_examples-msg:actual_delay_time-val is deprecated.  Use rtt_actionlib_examples-msg:actual_delay_time instead.")
  (actual_delay_time m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SomeActionResult>) ostream)
  "Serializes a message object of type '<SomeActionResult>"
  (cl:let ((__sec (cl:floor (cl:slot-value msg 'actual_delay_time)))
        (__nsec (cl:round (cl:* 1e9 (cl:- (cl:slot-value msg 'actual_delay_time) (cl:floor (cl:slot-value msg 'actual_delay_time)))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SomeActionResult>) istream)
  "Deserializes a message object of type '<SomeActionResult>"
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'actual_delay_time) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SomeActionResult>)))
  "Returns string type for a message object of type '<SomeActionResult>"
  "rtt_actionlib_examples/SomeActionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SomeActionResult)))
  "Returns string type for a message object of type 'SomeActionResult"
  "rtt_actionlib_examples/SomeActionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SomeActionResult>)))
  "Returns md5sum for a message object of type '<SomeActionResult>"
  "f94f292a8b4903014f3007574d0b6448")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SomeActionResult)))
  "Returns md5sum for a message object of type 'SomeActionResult"
  "f94f292a8b4903014f3007574d0b6448")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SomeActionResult>)))
  "Returns full string definition for message of type '<SomeActionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%duration actual_delay_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SomeActionResult)))
  "Returns full string definition for message of type 'SomeActionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%duration actual_delay_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SomeActionResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SomeActionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SomeActionResult
    (cl:cons ':actual_delay_time (actual_delay_time msg))
))
