/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/rosgraph_msgs/cmake/../msg/Clock.msg */
#ifndef ROSGRAPH_MSGS_BOOST_SERIALIZATION_CLOCK_H
#define ROSGRAPH_MSGS_BOOST_SERIALIZATION_CLOCK_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <rosgraph_msgs/Clock.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::rosgraph_msgs::Clock_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("clock",m.clock);
}

} // namespace serialization
} // namespace boost

#endif // ROSGRAPH_MSGS_BOOST_SERIALIZATION_CLOCK_H

