/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/rosgraph_msgs/cmake/../msg/Log.msg */
#ifndef ROSGRAPH_MSGS_BOOST_SERIALIZATION_LOG_H
#define ROSGRAPH_MSGS_BOOST_SERIALIZATION_LOG_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <rosgraph_msgs/Log.h>
#include <std_msgs/boost/Header.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::rosgraph_msgs::Log_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("level",m.level);
    a & make_nvp("name",m.name);
    a & make_nvp("msg",m.msg);
    a & make_nvp("file",m.file);
    a & make_nvp("function",m.function);
    a & make_nvp("line",m.line);
    a & make_nvp("topics",m.topics);
}

} // namespace serialization
} // namespace boost

#endif // ROSGRAPH_MSGS_BOOST_SERIALIZATION_LOG_H

