/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/CameraInfo.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_CAMERAINFO_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_CAMERAINFO_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/CameraInfo.h>
#include <std_msgs/boost/Header.h>
#include <sensor_msgs/boost/RegionOfInterest.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::CameraInfo_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("height",m.height);
    a & make_nvp("width",m.width);
    a & make_nvp("distortion_model",m.distortion_model);
    a & make_nvp("D",m.D);
    a & make_nvp("K",m.K);
    a & make_nvp("R",m.R);
    a & make_nvp("P",m.P);
    a & make_nvp("binning_x",m.binning_x);
    a & make_nvp("binning_y",m.binning_y);
    a & make_nvp("roi",m.roi);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_CAMERAINFO_H

