/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/ChannelFloat32.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_CHANNELFLOAT32_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_CHANNELFLOAT32_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/ChannelFloat32.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::ChannelFloat32_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("name",m.name);
    a & make_nvp("values",m.values);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_CHANNELFLOAT32_H

