/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/CompressedImage.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_COMPRESSEDIMAGE_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_COMPRESSEDIMAGE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/CompressedImage.h>
#include <std_msgs/boost/Header.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::CompressedImage_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("format",m.format);
    a & make_nvp("data",m.data);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_COMPRESSEDIMAGE_H

