/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/FluidPressure.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_FLUIDPRESSURE_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_FLUIDPRESSURE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/FluidPressure.h>
#include <std_msgs/boost/Header.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::FluidPressure_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("fluid_pressure",m.fluid_pressure);
    a & make_nvp("variance",m.variance);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_FLUIDPRESSURE_H

