/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/Image.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_IMAGE_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_IMAGE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/Image.h>
#include <std_msgs/boost/Header.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::Image_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("height",m.height);
    a & make_nvp("width",m.width);
    a & make_nvp("encoding",m.encoding);
    a & make_nvp("is_bigendian",m.is_bigendian);
    a & make_nvp("step",m.step);
    a & make_nvp("data",m.data);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_IMAGE_H

