/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/Imu.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_IMU_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_IMU_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/Imu.h>
#include <std_msgs/boost/Header.h>
#include <geometry_msgs/boost/Quaternion.h>
#include <geometry_msgs/boost/Vector3.h>
#include <geometry_msgs/boost/Vector3.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::Imu_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("orientation",m.orientation);
    a & make_nvp("orientation_covariance",m.orientation_covariance);
    a & make_nvp("angular_velocity",m.angular_velocity);
    a & make_nvp("angular_velocity_covariance",m.angular_velocity_covariance);
    a & make_nvp("linear_acceleration",m.linear_acceleration);
    a & make_nvp("linear_acceleration_covariance",m.linear_acceleration_covariance);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_IMU_H

