/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/JointState.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_JOINTSTATE_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_JOINTSTATE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/JointState.h>
#include <std_msgs/boost/Header.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::JointState_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("name",m.name);
    a & make_nvp("position",m.position);
    a & make_nvp("velocity",m.velocity);
    a & make_nvp("effort",m.effort);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_JOINTSTATE_H

