/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/JoyFeedback.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_JOYFEEDBACK_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_JOYFEEDBACK_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/JoyFeedback.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::JoyFeedback_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("type",m.type);
    a & make_nvp("id",m.id);
    a & make_nvp("intensity",m.intensity);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_JOYFEEDBACK_H

