/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/LaserEcho.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_LASERECHO_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_LASERECHO_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/LaserEcho.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::LaserEcho_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("echoes",m.echoes);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_LASERECHO_H

