/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/MagneticField.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_MAGNETICFIELD_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_MAGNETICFIELD_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/MagneticField.h>
#include <std_msgs/boost/Header.h>
#include <geometry_msgs/boost/Vector3.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::MagneticField_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("magnetic_field",m.magnetic_field);
    a & make_nvp("magnetic_field_covariance",m.magnetic_field_covariance);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_MAGNETICFIELD_H

