/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/MultiDOFJointState.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_MULTIDOFJOINTSTATE_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_MULTIDOFJOINTSTATE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/MultiDOFJointState.h>
#include <std_msgs/boost/Header.h>
#include <geometry_msgs/boost/Transform.h>
#include <geometry_msgs/boost/Twist.h>
#include <geometry_msgs/boost/Wrench.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::MultiDOFJointState_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("joint_names",m.joint_names);
    a & make_nvp("transforms",m.transforms);
    a & make_nvp("twist",m.twist);
    a & make_nvp("wrench",m.wrench);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_MULTIDOFJOINTSTATE_H

