/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/NavSatStatus.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_NAVSATSTATUS_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_NAVSATSTATUS_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/NavSatStatus.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::NavSatStatus_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("status",m.status);
    a & make_nvp("service",m.service);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_NAVSATSTATUS_H

