/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/PointCloud2.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_POINTCLOUD2_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_POINTCLOUD2_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/PointCloud2.h>
#include <std_msgs/boost/Header.h>
#include <sensor_msgs/boost/PointField.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::PointCloud2_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("height",m.height);
    a & make_nvp("width",m.width);
    a & make_nvp("fields",m.fields);
    a & make_nvp("is_bigendian",m.is_bigendian);
    a & make_nvp("point_step",m.point_step);
    a & make_nvp("row_step",m.row_step);
    a & make_nvp("data",m.data);
    a & make_nvp("is_dense",m.is_dense);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_POINTCLOUD2_H

