/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/PointField.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_POINTFIELD_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_POINTFIELD_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/PointField.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::PointField_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("name",m.name);
    a & make_nvp("offset",m.offset);
    a & make_nvp("datatype",m.datatype);
    a & make_nvp("count",m.count);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_POINTFIELD_H

