/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/PointCloud.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_POINTCLOUD_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_POINTCLOUD_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/PointCloud.h>
#include <std_msgs/boost/Header.h>
#include <geometry_msgs/boost/Point32.h>
#include <sensor_msgs/boost/ChannelFloat32.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::PointCloud_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("points",m.points);
    a & make_nvp("channels",m.channels);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_POINTCLOUD_H

