/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/Range.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_RANGE_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_RANGE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/Range.h>
#include <std_msgs/boost/Header.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::Range_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("radiation_type",m.radiation_type);
    a & make_nvp("field_of_view",m.field_of_view);
    a & make_nvp("min_range",m.min_range);
    a & make_nvp("max_range",m.max_range);
    a & make_nvp("range",m.range);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_RANGE_H

