/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/RegionOfInterest.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_REGIONOFINTEREST_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_REGIONOFINTEREST_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/RegionOfInterest.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::RegionOfInterest_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("x_offset",m.x_offset);
    a & make_nvp("y_offset",m.y_offset);
    a & make_nvp("height",m.height);
    a & make_nvp("width",m.width);
    a & make_nvp("do_rectify",m.do_rectify);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_REGIONOFINTEREST_H

