/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/RelativeHumidity.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_RELATIVEHUMIDITY_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_RELATIVEHUMIDITY_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/RelativeHumidity.h>
#include <std_msgs/boost/Header.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::RelativeHumidity_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("relative_humidity",m.relative_humidity);
    a & make_nvp("variance",m.variance);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_RELATIVEHUMIDITY_H

