/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/Temperature.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_TEMPERATURE_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_TEMPERATURE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/Temperature.h>
#include <std_msgs/boost/Header.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::Temperature_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("temperature",m.temperature);
    a & make_nvp("variance",m.variance);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_TEMPERATURE_H

