/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/sensor_msgs/cmake/../msg/TimeReference.msg */
#ifndef SENSOR_MSGS_BOOST_SERIALIZATION_TIMEREFERENCE_H
#define SENSOR_MSGS_BOOST_SERIALIZATION_TIMEREFERENCE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <sensor_msgs/TimeReference.h>
#include <std_msgs/boost/Header.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sensor_msgs::TimeReference_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("time_ref",m.time_ref);
    a & make_nvp("source",m.source);
}

} // namespace serialization
} // namespace boost

#endif // SENSOR_MSGS_BOOST_SERIALIZATION_TIMEREFERENCE_H

