/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/geometry_msgs/cmake/../msg/Point.msg */
#ifndef GEOMETRY_MSGS_BOOST_SERIALIZATION_POINT_H
#define GEOMETRY_MSGS_BOOST_SERIALIZATION_POINT_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <geometry_msgs/Point.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::geometry_msgs::Point_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("x",m.x);
    a & make_nvp("y",m.y);
    a & make_nvp("z",m.z);
}

} // namespace serialization
} // namespace boost

#endif // GEOMETRY_MSGS_BOOST_SERIALIZATION_POINT_H

