/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/geometry_msgs/cmake/../msg/Pose2D.msg */
#ifndef GEOMETRY_MSGS_BOOST_SERIALIZATION_POSE2D_H
#define GEOMETRY_MSGS_BOOST_SERIALIZATION_POSE2D_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <geometry_msgs/Pose2D.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::geometry_msgs::Pose2D_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("x",m.x);
    a & make_nvp("y",m.y);
    a & make_nvp("theta",m.theta);
}

} // namespace serialization
} // namespace boost

#endif // GEOMETRY_MSGS_BOOST_SERIALIZATION_POSE2D_H

