/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/geometry_msgs/cmake/../msg/Pose.msg */
#ifndef GEOMETRY_MSGS_BOOST_SERIALIZATION_POSE_H
#define GEOMETRY_MSGS_BOOST_SERIALIZATION_POSE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/boost/Point.h>
#include <geometry_msgs/boost/Quaternion.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::geometry_msgs::Pose_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("position",m.position);
    a & make_nvp("orientation",m.orientation);
}

} // namespace serialization
} // namespace boost

#endif // GEOMETRY_MSGS_BOOST_SERIALIZATION_POSE_H

