/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/geometry_msgs/cmake/../msg/QuaternionStamped.msg */
#ifndef GEOMETRY_MSGS_BOOST_SERIALIZATION_QUATERNIONSTAMPED_H
#define GEOMETRY_MSGS_BOOST_SERIALIZATION_QUATERNIONSTAMPED_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <geometry_msgs/QuaternionStamped.h>
#include <std_msgs/boost/Header.h>
#include <geometry_msgs/boost/Quaternion.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::geometry_msgs::QuaternionStamped_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("quaternion",m.quaternion);
}

} // namespace serialization
} // namespace boost

#endif // GEOMETRY_MSGS_BOOST_SERIALIZATION_QUATERNIONSTAMPED_H

