/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/geometry_msgs/cmake/../msg/TransformStamped.msg */
#ifndef GEOMETRY_MSGS_BOOST_SERIALIZATION_TRANSFORMSTAMPED_H
#define GEOMETRY_MSGS_BOOST_SERIALIZATION_TRANSFORMSTAMPED_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <geometry_msgs/TransformStamped.h>
#include <std_msgs/boost/Header.h>
#include <geometry_msgs/boost/Transform.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::geometry_msgs::TransformStamped_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("child_frame_id",m.child_frame_id);
    a & make_nvp("transform",m.transform);
}

} // namespace serialization
} // namespace boost

#endif // GEOMETRY_MSGS_BOOST_SERIALIZATION_TRANSFORMSTAMPED_H

