/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/geometry_msgs/cmake/../msg/TwistWithCovariance.msg */
#ifndef GEOMETRY_MSGS_BOOST_SERIALIZATION_TWISTWITHCOVARIANCE_H
#define GEOMETRY_MSGS_BOOST_SERIALIZATION_TWISTWITHCOVARIANCE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <geometry_msgs/TwistWithCovariance.h>
#include <geometry_msgs/boost/Twist.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::geometry_msgs::TwistWithCovariance_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("twist",m.twist);
    a & make_nvp("covariance",m.covariance);
}

} // namespace serialization
} // namespace boost

#endif // GEOMETRY_MSGS_BOOST_SERIALIZATION_TWISTWITHCOVARIANCE_H

