/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/geometry_msgs/cmake/../msg/Vector3Stamped.msg */
#ifndef GEOMETRY_MSGS_BOOST_SERIALIZATION_VECTOR3STAMPED_H
#define GEOMETRY_MSGS_BOOST_SERIALIZATION_VECTOR3STAMPED_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <geometry_msgs/Vector3Stamped.h>
#include <std_msgs/boost/Header.h>
#include <geometry_msgs/boost/Vector3.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::geometry_msgs::Vector3Stamped_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("vector",m.vector);
}

} // namespace serialization
} // namespace boost

#endif // GEOMETRY_MSGS_BOOST_SERIALIZATION_VECTOR3STAMPED_H

