/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/geometry_msgs/cmake/../msg/Wrench.msg */
#ifndef GEOMETRY_MSGS_BOOST_SERIALIZATION_WRENCH_H
#define GEOMETRY_MSGS_BOOST_SERIALIZATION_WRENCH_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <geometry_msgs/Wrench.h>
#include <geometry_msgs/boost/Vector3.h>
#include <geometry_msgs/boost/Vector3.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::geometry_msgs::Wrench_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("force",m.force);
    a & make_nvp("torque",m.torque);
}

} // namespace serialization
} // namespace boost

#endif // GEOMETRY_MSGS_BOOST_SERIALIZATION_WRENCH_H

