/* Auto-generated by create_boost_header.py for file /opt/ros/hydro/share/tf/cmake/../msg/tfMessage.msg */
#ifndef TF_BOOST_SERIALIZATION_TFMESSAGE_H
#define TF_BOOST_SERIALIZATION_TFMESSAGE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <tf/tfMessage.h>
#include <geometry_msgs/boost/TransformStamped.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::tf::tfMessage_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("transforms",m.transforms);
}

} // namespace serialization
} // namespace boost

#endif // TF_BOOST_SERIALIZATION_TFMESSAGE_H

